[package]
rust-version.workspace = true
name = "sdkwork-api-prompts-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "sdkwork-api-prompts-standalone-gateway"
path = "src/main.rs"


[lints]
workspace = true
[dependencies]
sdkwork-api-prompts-assembly.workspace = true
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sdkwork-web-bootstrap = { workspace = true }
sdkwork-iam-web-adapter = { workspace = true }
sdkwork-utils-rust = { workspace = true }
